[project]
name = "wiki-graph"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.12",
    "mypy>=1.15.0",
    "neo4j>=5.28.0",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.7.1",
    "ruff>=0.9.4",
    "tenacity>=9.0.0",
]
