# Общие настройки
line-length = 120
exclude = ["cli.py", "cli/*", "*/test_*.py"]

[analyze]
detect-string-imports = true

[lint.extend-per-file-ignores]
"__init__.py" = ["N999"]

[lint.pylint]
allow-magic-value-types = []
max-nested-blocks = 3
max-statements = 15
max-bool-expr = 3
max-branches = 5
max-locals = 5
max-returns = 3

[lint]
preview = true
select = [
    "F", "E", "W", "C90", "I", "N", "YTT", "ANN", "ASYNC", "S", "BLE", "FBT", "B", "A", "COM", "C4", "DTZ", "T10", "EM",
    "FA", "ISC", "ICN", "LOG", "G", "INP", "PIE", "T20", "PYI", "PT", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TCH",
    "INT", "ARG", "PTH", "TD", "FIX", "ERA", "PL", "TRY", "FLY", "PERF", "FURB", "RUF", "Q"
]
ignore = [
    "RUF001", "RUF002", "RUF003", "FA100", "FA102", "PLC0206", "ANN401", "TID251",
    "FIX002", "TD003", "TD002"  # Ignore TODOs
]

[lint.flake8-tidy-imports.banned-api]
"typing.Dict".msg = "Use `dict` instead."
"typing.List".msg = "Use `list` instead."
"typing.Set".msg = "Use `set` instead."
"typing.Tuple".msg = "Use `tuple` instead."
"typing.Optional".msg = "Use `... | None` instead."
"typing.Union".msg = "Use `... | ...` instead."
"pandas".msg = "Do not use this lib."
"numpy".msg = "Do not use this lib."
